services:
  db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  bankeriseRetailMock-api:
    container_name: 
    image: 
    environment:
      SPRING_DATASOURCE_URL: 
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
  bankeriseRetailMock-react:
    container_name: 
    image: 
    build:
      context: frontend/react
      args:
        api_base_url: 
    ports:
      - 
    depends_on:
      - 
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: